all: program0 program1 program2 program3

program0:
	g++ hw6.0-aaronjohnson.cpp -l pthread -o hw6.0-aaronjohnson

program1:
	g++ hw6.1-aaronjohnson.cpp -l pthread -o hw6.1-aaronjohnson

program2:
	g++ hw6.2-aaronjohnson.cpp -l pthread -o hw6.2-aaronjohnson

program3:
	g++ hw6.3-aaronjohnson.cpp -l pthread -o hw6.3-aaronjohnson

clean:
	rm hw6.0-aaronjohnson hw6.1-aaronjohnson hw6.2-aaronjohnson hw6.3-aaronjohnson