all: program0 program1 program2 program3

program0:
	g++ -std=c++11 program0.cpp -l pthread -o program0

program1:
	g++ -std=c++11 program1.cpp -l pthread -o program1

program2:
	g++ -std=c++11 program2.cpp -l pthread -o program2

program3:
	g++ -std=c++11 program3.cpp -l pthread -o program3

clean:
	rm program0 program1 program2 program3